<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Plans;
use App\Models\Category;
use App\Models\ControlCategories;

class ClientChannels extends Model
{
    use HasFactory;
 //removing autoGenerated timeStamps
 public $timestamps=false;
 /**
  *
  * @var string[]
 */
protected $table = 'clientchannels';
 //Fillable 
 protected $fillable=[
     'id',
     'user',
     'plan',
     'category' ,
     'controlCategory',
     'controlChannel',
     'channelId',
     'enabled',
     'startDate',
     'updateDate',
     'endDate',
   
 ];



 // Casting what variables are expected to be
 protected $cast=[
    'plan'=> 'integer',
    'user'=> 'integer',
    'category'=> 'integer' ,
    'controlChannel'=> 'integer',
    'channelId'=> 'string',
    'enabled'=> 'boolean',
    'startDate'=> 'timpestamp',
    'updateDate'=> 'timestamp',
    'endDate'=> 'timestamp',
 ];

 
    public function getPlan()
    {
        return $this->belongsTo(Plans::class, 'plan', 'id');
    }

}
