<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Plans;
use App\Models\Category;
use App\Models\ControlCategories;

class ClientCategories extends Model
{
    use HasFactory;
 //removing autoGenerated timeStamps
 public $timestamps=false;
 /**
  *
  * @var string[]
 */
protected $table = 'clientcategories';
 //Fillable 
 protected $fillable = ['categoryid', "plan", "category", "enabled"];



 // Casting what variables are expected to be
 protected $cast=[
    'plan'=> 'integer',
    'user'=> 'integer',
    'category'=> 'integer' ,
    'controlChannel'=> 'integer',
    'channelId'=> 'string',
    'enabled'=> 'boolean',
    'startDate'=> 'timpestamp',
    'updateDate'=> 'timestamp',
    'endDate'=> 'timestamp',
 ];

}
