<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Products;
use App\Models\ClientChannels;

class ControlCategories extends Model
{
    use HasFactory;
    //removing autoGenerated timeStamps
    public $timestamps=false;
    protected $table = 'controlcategories';
    /**
     *
     * @var string[]
    */
    //Fillable 
    protected $fillable=[
        'id',
        'product',
        'categoryId' ,
        'name',
        'enabled',
        'startDate',
        'updateDate',
        'endDate',
        'type'
    ];

   

    // Casting what variables are expected to be
    protected $cast=[
        'product'=>'integer',
        'categoryId' => 'integer' ,
        'name' => 'string',
        'enabled' => 'boolean',
        'startDate' => 'timestamp',
        'updateDate' => 'timestamp',
        'endDate' => 'timestamp',
        'type' => 'string'
    ];

    public function channels()
    {
        return $this->hasMany(ClientChannels::class, "controlCategory", "id");
    }
    public function controlchannels()
    {
        return $this->hasMany(Channels::class, "category", "id");
    }
    public function clientcategories()
    {
        return $this->hasMany(ClientCategories::class, "category", "id");
    }
}
