<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Products;
use App\Models\Business;
use App\Models\User;

class Invoices extends Model
{
    use HasFactory;

    //removing autoGenerated timeStamps
    public $timestamps=false;
    /**
     *
     * @var string[]
    */
    //Fillable 
    protected $fillable=[
        'id',
        'user',
        'business',
        'product',
        'sub' ,
        'stripe_tid',
        'plan',
        'billing_name',
        'billing_address',
        'billing_email',
        'invoice_url',
        'pay_method',
        'pay_amount',
        'creationDate',
        'joinDate'
    ];

    //Hidden not visible to any user
    protected $hidden=[
        'stripe_tid'
    ];

    // Casting what variables are expected to be
    protected $cast=[
        'user'=>'integer',
        'business'=>'integer',
        'product'=>'integer',
        'sub' =>'string',
        'stripe_tid' => 'string',
        'plan'=>'integer',
        'billing_name' => 'string',
        'billing_address' => 'string',
        'billing_email' => 'string',
        'invoice_url' => 'string',
        'pay_method' => 'string',
        'pay_amount' => 'float',
        'creationDate'=>'timestamp',
        'joinDate' => 'timestamp'
    ];

    
    public function getProduct()
    {
        return $this->belongsTo(Products::class, 'product', 'id');
    }
    
    public function getBusiness()
    {
        return $this->belongsTo(Business::class, 'business', 'id');
    }
    public function getUser()
    {
        return $this->belongsTo(User::class, 'user', 'id');
    }
}
