<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Logs extends Model
{
    use HasFactory;
    //removing autoGenerated timeStamps
    public $timestamps=false;
    /**
     *
     * @var string[]
    */
    //Fillable 
    protected $fillable=[
        'id',
        'serverId',
        'type',
        'log',
        'creationDate',
        'joinDate'
    ];

    protected $cast=[
        'serverId'=>'integer',
        'log'=>'integer',
        'type' =>'string',
        'creationDate'=>'timestamp',
        'joinDate' => 'timestamp'
    ];
}
