<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Products;
use App\Models\User;

class Orders extends Model
{
    use HasFactory;

    //removing autoGenerated timeStamps
    public $timestamps=false;
    /**
     *
     * @var string[]
    */
    //Fillable 
    protected $fillable=[
        'id',
        'user',
        'product',
        'sub' ,
        'stripeTId',
        'plan',
        'billing_name',
        'billing_address',
        'billing_email',
        'pay_method',
        'pay_amount',
        'creationDate',
        'joinDate'
    ];

    //Hidden not visible to any user
    protected $hidden=[
        'stripePId'
    ];

    // Casting what variables are expected to be
    protected $cast=[
        'user'=>'integer',
        'product'=>'integer',
        'sub' =>'string',
        'stripePId' => 'string',
        'plan'=>'integer',
        'billing_name' => 'string',
        'billing_address' => 'string',
        'billing_email' => 'string',
        'pay_method' => 'string',
        'pay_amount' => 'float',
        'creationDate'=>'timestamp',
        'joinDate' => 'timestamp'
    ];
}
