<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permissions extends Model
{
    use HasFactory;
    //removing autoGenerated timeStamps
    public $timestamps=false;
    /**
     *
     * @var string[]
    */
    //Fillable 
    protected $fillable=[
        'id',
        'user',
        'business' ,
        'server' ,
        'discordId',
        'permission',
        'permission_token',
        'last_update',
        
    ];

   

    // Casting what variables are expected to be
    protected $cast=[
        'user'=>'integer',
        'business'=>'integer', 
        'server'=>'integer', 
        'dicordId' => 'string',
        'permission' => 'integer',
        'permission_token' => 'string',
        'last_update' => 'timestamp',
        
    ];
}
